resource_types:
    - name: pull-request
      type: docker-image
      source:
          repository: jtarchie/pr

resources:
    - name: magic-modules
      type: git
      source:
          uri: git@github.com:ndmckinley/magic-modules.git
          branch: ci-server
          private_key: ((repo_key))

    - name: terraform
      type: git
      source:
          uri: git@github.com:ndmckinley/terraform-provider-google.git
          branch: master
          private_key: ((repo_key))

    - name: terraform-intermediate
      type: git
      source:
          uri: git@github.com:ndmckinley/terraform-provider-google.git
          branch: magic_modules
          private_key: ((repo_key))

    - name: terraform-pr
      type: pull-request
      source:
          access_token: ((repo_access))
          private_key: ((repo_key))
          repo: ndmckinley/terraform-provider-google
          base: magic_modules

jobs:
    - name: mm-generate
      plan:
          - aggregate:
                - get: magic-modules
                - get: terraform
          - task: generate
            file: magic-modules/ci/generate.yml
          - put: terraform-intermediate
            params:
                repository: magic-modules/build/terraform

    - name: terraform-test
      plan:
          - get: terraform-intermediate
            passed: [mm-generate]
          - task: test
            file: terraform/ci/unit_tests.yml
          - put: terraform-pr
